spring:
  application:
    name: easyenroll_user
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sms_user?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 1234

mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.ly.easyenroll_sms.pojo

server:
  port: 8090